version: '3.8'

services:
  logstash:
    build:
      context: ./logstash
    container_name: logstash
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - app-network
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  service1:
    build:
      context: ./service1
    container_name: service1
    networks:
      - app-network
    expose:
      - "5001"
    volumes:
      - ./logs/service1:/app/logs

  service2:
    build:
      context: ./service2
    container_name: service2
    networks:
      - app-network
    expose:
      - "5002"
    volumes:
      - ./logs/service2:/app/logs

networks:
  app-network:
    driver: bridge  # Внутренняя сеть